"""The reporter node's structured prompt -- ported from
BusinessAnalyst.execute()."""
from __future__ import annotations

import json
from datetime import datetime

from backend.data.models import AssetMetrics, UserPrefs


def build_report_prompt(metrics: list[AssetMetrics], user_prefs: UserPrefs) -> str:
    top_5 = metrics[:5]
    top_5_context = json.dumps([m.model_dump() for m in top_5])
    top_3_names = [m.name for m in metrics[:3]]
    top_3_str = ", ".join(top_3_names)
    current_date = datetime.now().strftime("%B %d, %Y")

    def pick(i: int) -> str:
        return top_3_names[i] if len(top_3_names) > i else f"Asset {i + 1}"

    return f"""
You are a Senior Investment Strategist for the Indian Market.

**Quantitative Analysis (Top Screened Assets - JSON Format):**
{top_5_context}

**Top 3 Quantitative Picks:** {top_3_str}

**Task:**
Generate a structured investment report following the EXACT format below. Do not deviate.

**Required Output Format:**

**Date:** {current_date}
**Client Profile:** {user_prefs.risk} Investor | Target: {user_prefs.target_return} | {user_prefs.horizon} | Goal: {user_prefs.goal}

---

# **Executive Summary**
(Max 100 words: Synthesize the strategy tailored to the user's goal.)

# **Top 3 Recommendations (Ranked)**
1. **{pick(0)}**: (Max 100 words: Focus on selection justification and fundamentals like P/E, ROE.)
2. **{pick(1)}**: (Max 100 words: Focus on selection justification and fundamentals.)
3. **{pick(2)}**: (Max 100 words: Focus on selection justification and fundamentals.)

# **Portfolio Strategy**
(Max 100 words: How these 3 assets fit together.)

# **Indian Market Context**
(Max 50 words: Relevant factors like Inflation, RBI policies, Sector growth.)

# **Risk Factors**
(Max 50 words: Warning about volatility or market conditions.)
---
# **Disclaimer**
"This report is generated by AI for informational purposes only and does not constitute financial advice. Past performance is not indicative of future results. Please consult a SEBI-registered investment advisor before making any investment decisions."

**Constraints:**
- **Tone:** Formal, professional, encouraging.
- **Currency:** Use ₹ symbol.
- **Consistency:** You MUST recommend the Top 3 Quantitative Picks listed above in that exact order.
- **Data:** Use the provided JSON data accurately.
"""
