# Test secrets file for local development
GEMINI_API_KEY = "AIzaSyCWmmOu6TkkRcdFuXVw2NF8jOmBJO8XVhU"
SUPABASE_KEY = "https://yycvcqdhhjoxaeojkbfp.supabase.co" 
SUPABASE_URL = "sb_publishable_46yePtoIBXOhS8z04oi8zQ_obR8xok3"
